version: "3.9"
services:
  api:
    build: ./backend
    volumes:
      - ./backend:/go/src/app
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: eqalpha/keydb
    expose:
      - 6379
    volumes:
      - dbdata:/data

volumes:
  dbdata:
