version: "3.9"
services:
  api:
    build:
      context: ../
      dockerfile: ./scripts/dev.Dockerfile
    command: "sh scripts/dev.sh"
    volumes:
      - ../:/app
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: eqalpha/keydb
    expose:
      - 6379
    volumes:
      - dbdata:/data

volumes:
  dbdata:
