name = "workers"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-11-13"

[build]
command = "pnpm install && pnpm build"

[build.upload]
format = "module"
main = "./dist/worker.mjs"
